#!/usr/bin/env python3
"""
Build derived occlusion assets from an existing STEP asset manifest.

The script creates variants such as:
  - points/<sample_id>__occ_000.npz
  - images/<sample_id>__occ_000/view_000.png
  - masks/<sample_id>__occ_000/view_000_mask.png
  - steps/<sample_id>__occ_000.step, optionally
  - labels/<sample_id>__occ_000.json

Occlusion parameters are stored in unit-cube coordinates [0, 1]^3. Existing
point clouds generated by build_step_assets.py are expected to be in centered
unit-cube coordinates [-0.5, 0.5]^3, so the conversion is explicit.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import signal
import sys
from dataclasses import dataclass
from itertools import repeat
from multiprocessing import Pool
from pathlib import Path
from typing import Any, Iterable, Optional, Sequence

import numpy as np
import trimesh
from PIL import Image
from PIL import ImageDraw
from PIL import ImageFilter
from tqdm import tqdm

SRC_ROOT = Path(__file__).resolve().parents[1]
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from cad_data_gen.build_step_assets import (  # noqa: E402
    _view_basis,
    get_view_fronts,
    load_step_as_mesh,
    normalize_trimesh_unit_cube,
    render_step_views_with_blender,
    render_views_to_png,
    resolve_blender_bin,
)
from cad_data_gen.step_mesh_backends import parse_fallback_backends  # noqa: E402

try:
    import cadquery as cq
except ModuleNotFoundError:
    cq = None


VALID_DIMS = {"point_cloud", "image", "step"}
VALID_MODES = {"cutout", "occluder", "mixed"}


@dataclass(frozen=True)
class OcclusionSpec:
    source_sample_id: str
    variant_id: str
    variant_sample_id: str
    mode: str
    target_dims: tuple[str, ...]
    primitive: str
    center_unit: tuple[float, float, float]
    size_unit: tuple[float, float, float]
    seed: int
    views: int

    def to_dict(self) -> dict[str, Any]:
        return {
            "source_sample_id": self.source_sample_id,
            "variant_id": self.variant_id,
            "variant_sample_id": self.variant_sample_id,
            "mode": self.mode,
            "target_dims": list(self.target_dims),
            "primitive": self.primitive,
            "center_unit": list(self.center_unit),
            "size_unit": list(self.size_unit),
            "seed": self.seed,
            "views": self.views,
        }


@dataclass(frozen=True)
class ProcessArgs:
    source_assets_dir: Path
    step_root: Path
    output_dir: Path
    target_dims: tuple[str, ...]
    mode: str
    num_views: int
    img_size: int
    camera_distance: float
    render_width: int
    render_height: int
    render_backend: str
    blender_bin: str
    blender_script: Optional[Path]
    blender_engine: str
    blender_samples: int
    blender_style: str
    blender_device: str
    step_mesh_backend: str
    step_mesh_fallback_backends: tuple[str, ...]
    step_mesh_work_dir: Optional[Path]
    step_mesh_format: str
    freecad_cmd: str
    step_mesh_timeout_s: Optional[float]
    foreground_occluder_size_min: float
    foreground_occluder_size_max: float
    foreground_occluder_depth: float
    triangle_face_tol: float
    angle_tol_rads: float
    variants_per_sample: int
    seed: int
    size_min: float
    size_max: float
    min_removed_ratio: float
    max_removed_ratio: float
    max_spec_attempts: int
    num_points: Optional[int]
    fixed_num_points: bool
    occluder_color: tuple[int, int, int]
    highlight_cutout: bool
    highlight_color: tuple[int, int, int]
    highlight_alpha: float
    outline_color: tuple[int, int, int]
    outline_width: int
    skip_existing: bool


def _as_float_list(values: Sequence[float]) -> list[float]:
    return [float(v) for v in values]


def _json_dump(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=True, indent=2, sort_keys=True)
        f.write("\n")


def _stable_seed(base_seed: int, sample_id: str, variant_index: int) -> int:
    raw = f"{base_seed}:{sample_id}:{variant_index}".encode("utf-8")
    digest = hashlib.sha256(raw).digest()
    return int.from_bytes(digest[:8], "little") % (2**32 - 1)


def _parse_dims(raw: str) -> tuple[str, ...]:
    dims = tuple(part.strip() for part in raw.split(",") if part.strip())
    unknown = sorted(set(dims) - VALID_DIMS)
    if unknown:
        raise ValueError(f"unknown target dims: {unknown}")
    if not dims:
        raise ValueError("at least one target dim is required")
    return dims


def _parse_color(raw: str) -> tuple[int, int, int]:
    parts = [int(p.strip()) for p in raw.split(",")]
    if len(parts) != 3 or any(p < 0 or p > 255 for p in parts):
        raise ValueError("--occluder-color must be R,G,B with values in [0,255]")
    return tuple(parts)


def _load_manifest(path: Path, limit: Optional[int]) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            records.append(json.loads(line))
            if limit is not None and len(records) >= limit:
                break
    return records


def _unit_points(points_centered: np.ndarray) -> np.ndarray:
    return np.clip(np.asarray(points_centered, dtype=np.float64) + 0.5, 0.0, 1.0)


def _box_bounds(
    center_unit: Sequence[float],
    size_unit: Sequence[float],
) -> tuple[np.ndarray, np.ndarray]:
    center = np.asarray(center_unit, dtype=np.float64)
    size = np.asarray(size_unit, dtype=np.float64)
    return center - size * 0.5, center + size * 0.5


def _points_in_unit_box(
    points_centered: np.ndarray,
    center_unit: Sequence[float],
    size_unit: Sequence[float],
) -> np.ndarray:
    points = _unit_points(points_centered)
    low, high = _box_bounds(center_unit, size_unit)
    return np.all((points >= low) & (points <= high), axis=1)


def _mesh_face_mask_in_box(
    mesh_centered: trimesh.Trimesh,
    center_unit: Sequence[float],
    size_unit: Sequence[float],
) -> np.ndarray:
    centers_unit = np.asarray(mesh_centered.triangles_center, dtype=np.float64) + 0.5
    low, high = _box_bounds(center_unit, size_unit)
    return np.all((centers_unit >= low) & (centers_unit <= high), axis=1)


def _cutout_mesh_by_box(
    mesh_centered: trimesh.Trimesh,
    spec: OcclusionSpec,
) -> tuple[trimesh.Trimesh, dict[str, float]]:
    removed_faces = _mesh_face_mask_in_box(
        mesh_centered,
        spec.center_unit,
        spec.size_unit,
    )
    keep_faces = ~removed_faces
    removed_ratio = float(removed_faces.mean()) if len(removed_faces) else 0.0
    if not keep_faces.any():
        raise ValueError("mesh cutout removed all faces")

    mesh = mesh_centered.copy()
    mesh.update_faces(keep_faces)
    mesh.remove_unreferenced_vertices()
    if len(mesh.faces) == 0 or len(mesh.vertices) == 0:
        raise ValueError("mesh cutout produced an empty mesh")
    return mesh, {"mesh_face_removed_ratio": removed_ratio}


def _convex_hull(points: np.ndarray) -> list[tuple[float, float]]:
    pts = sorted({(float(x), float(y)) for x, y in points})
    if len(pts) <= 1:
        return pts

    def cross(
        origin: tuple[float, float],
        a: tuple[float, float],
        b: tuple[float, float],
    ) -> float:
        return (a[0] - origin[0]) * (b[1] - origin[1]) - (
            a[1] - origin[1]
        ) * (b[0] - origin[0])

    lower: list[tuple[float, float]] = []
    for point in pts:
        while len(lower) >= 2 and cross(lower[-2], lower[-1], point) <= 0:
            lower.pop()
        lower.append(point)

    upper: list[tuple[float, float]] = []
    for point in reversed(pts):
        while len(upper) >= 2 and cross(upper[-2], upper[-1], point) <= 0:
            upper.pop()
        upper.append(point)

    return lower[:-1] + upper[:-1]


def _box_corners(center_unit: Sequence[float], size_unit: Sequence[float]) -> np.ndarray:
    low, high = _box_bounds(center_unit, size_unit)
    return np.asarray(
        [
            [x, y, z]
            for x in (low[0], high[0])
            for y in (low[1], high[1])
            for z in (low[2], high[2])
        ],
        dtype=np.float64,
    )


def _project_unit_points(
    points_unit: np.ndarray,
    mesh_vertices_unit: np.ndarray,
    front: Sequence[float],
    img_size: int,
) -> np.ndarray:
    right, true_up, _ = _view_basis(front)
    centered_mesh = np.asarray(mesh_vertices_unit, dtype=np.float64) - np.array(
        [0.5, 0.5, 0.5]
    )
    mesh_xy = np.stack([centered_mesh @ right, centered_mesh @ true_up], axis=1)
    span = float(np.max(np.ptp(mesh_xy, axis=0)))
    if span < 1e-8:
        raise ValueError("projected mesh is degenerate")

    centered_points = np.asarray(points_unit, dtype=np.float64) - np.array(
        [0.5, 0.5, 0.5]
    )
    xy = np.stack([centered_points @ right, centered_points @ true_up], axis=1)
    pad = img_size * 0.12
    scale = (img_size - 2 * pad) / span
    pixels = np.empty_like(xy)
    pixels[:, 0] = xy[:, 0] * scale + img_size / 2.0
    pixels[:, 1] = img_size / 2.0 - xy[:, 1] * scale
    return pixels


def _project_unit_points_with_depth(
    points_unit: np.ndarray,
    mesh_vertices_unit: np.ndarray,
    front: Sequence[float],
    img_size: int,
) -> tuple[np.ndarray, np.ndarray]:
    right, true_up, direction = _view_basis(front)
    centered_mesh = np.asarray(mesh_vertices_unit, dtype=np.float64) - np.array(
        [0.5, 0.5, 0.5]
    )
    mesh_xy = np.stack([centered_mesh @ right, centered_mesh @ true_up], axis=1)
    span = float(np.max(np.ptp(mesh_xy, axis=0)))
    if span < 1e-8:
        raise ValueError("projected mesh is degenerate")

    centered_points = np.asarray(points_unit, dtype=np.float64) - np.array(
        [0.5, 0.5, 0.5]
    )
    xy = np.stack([centered_points @ right, centered_points @ true_up], axis=1)
    z = centered_points @ direction
    pad = img_size * 0.12
    scale = (img_size - 2 * pad) / span
    pixels = np.empty_like(xy)
    pixels[:, 0] = xy[:, 0] * scale + img_size / 2.0
    pixels[:, 1] = img_size / 2.0 - xy[:, 1] * scale
    return pixels, z


def _rasterize_depth(
    pixels: np.ndarray,
    depths: np.ndarray,
    faces: np.ndarray,
    img_size: int,
) -> tuple[np.ndarray, np.ndarray]:
    z_buffer = np.full((img_size, img_size), -np.inf, dtype=np.float64)
    mask = np.zeros((img_size, img_size), dtype=bool)
    for tri in np.asarray(faces, dtype=np.int32):
        pts = pixels[tri]
        min_xy = np.floor(pts.min(axis=0)).astype(int)
        max_xy = np.ceil(pts.max(axis=0)).astype(int)
        min_x = max(0, min_xy[0])
        min_y = max(0, min_xy[1])
        max_x = min(img_size - 1, max_xy[0])
        max_y = min(img_size - 1, max_xy[1])
        if min_x > max_x or min_y > max_y:
            continue

        p0, p1, p2 = pts
        denom = (p1[1] - p2[1]) * (p0[0] - p2[0]) + (p2[0] - p1[0]) * (
            p0[1] - p2[1]
        )
        if abs(float(denom)) < 1e-12:
            continue

        yy, xx = np.mgrid[min_y : max_y + 1, min_x : max_x + 1]
        px = xx + 0.5
        py = yy + 0.5
        w0 = ((p1[1] - p2[1]) * (px - p2[0]) + (p2[0] - p1[0]) * (py - p2[1])) / denom
        w1 = ((p2[1] - p0[1]) * (px - p2[0]) + (p0[0] - p2[0]) * (py - p2[1])) / denom
        w2 = 1.0 - w0 - w1
        inside = (w0 >= -1e-6) & (w1 >= -1e-6) & (w2 >= -1e-6)
        if not inside.any():
            continue

        z_tri = depths[tri]
        z_pixels = w0 * z_tri[0] + w1 * z_tri[1] + w2 * z_tri[2]
        current = z_buffer[min_y : max_y + 1, min_x : max_x + 1]
        update = inside & (z_pixels > current)
        if not update.any():
            continue
        current[update] = z_pixels[update]
        mask[min_y : max_y + 1, min_x : max_x + 1][update] = True
    return z_buffer, mask


def _box_mesh_unit(
    center_unit: Sequence[float],
    size_unit: Sequence[float],
) -> tuple[np.ndarray, np.ndarray]:
    low, high = _box_bounds(center_unit, size_unit)
    x0, y0, z0 = low
    x1, y1, z1 = high
    vertices = np.asarray(
        [
            [x0, y0, z0],
            [x1, y0, z0],
            [x1, y1, z0],
            [x0, y1, z0],
            [x0, y0, z1],
            [x1, y0, z1],
            [x1, y1, z1],
            [x0, y1, z1],
        ],
        dtype=np.float64,
    )
    faces = np.asarray(
        [
            [0, 1, 2],
            [0, 2, 3],
            [4, 6, 5],
            [4, 7, 6],
            [0, 4, 5],
            [0, 5, 1],
            [1, 5, 6],
            [1, 6, 2],
            [2, 6, 7],
            [2, 7, 3],
            [3, 7, 4],
            [3, 4, 0],
        ],
        dtype=np.int32,
    )
    return vertices, faces


def _box_mask_for_view(
    mesh_centered: trimesh.Trimesh,
    spec: OcclusionSpec,
    front: Sequence[float],
    img_size: int,
) -> Image.Image:
    vertices_unit = np.asarray(mesh_centered.vertices, dtype=np.float64) + 0.5
    box_pixels = _project_unit_points(
        _box_corners(spec.center_unit, spec.size_unit),
        vertices_unit,
        front,
        img_size,
    )
    hull = _convex_hull(box_pixels)
    mask = Image.new("L", (img_size, img_size), 0)
    if len(hull) >= 3:
        draw = ImageDraw.Draw(mask)
        draw.polygon(hull, fill=255)
    return mask


def _visible_box_mask_for_view(
    mesh_centered: trimesh.Trimesh,
    spec: OcclusionSpec,
    front: Sequence[float],
    img_size: int,
    depth_epsilon: float = 0.01,
) -> Image.Image:
    model_vertices = np.asarray(mesh_centered.vertices, dtype=np.float64) + 0.5
    model_faces = np.asarray(mesh_centered.faces, dtype=np.int32)
    model_pixels, model_depths = _project_unit_points_with_depth(
        model_vertices,
        model_vertices,
        front,
        img_size,
    )
    model_z, model_mask = _rasterize_depth(
        model_pixels,
        model_depths,
        model_faces,
        img_size,
    )

    box_vertices, box_faces = _box_mesh_unit(spec.center_unit, spec.size_unit)
    box_pixels, box_depths = _project_unit_points_with_depth(
        box_vertices,
        model_vertices,
        front,
        img_size,
    )
    box_z, box_mask = _rasterize_depth(
        box_pixels,
        box_depths,
        box_faces,
        img_size,
    )
    visible = box_mask & model_mask & (box_z >= model_z - depth_epsilon)
    return Image.fromarray((visible.astype(np.uint8) * 255), mode="L")


def _uses_foreground_occluder(args: ProcessArgs, spec: OcclusionSpec) -> bool:
    return args.render_backend == "blender-step" and spec.mode == "occluder"


def _foreground_shape_points(
    shape: str,
    center: np.ndarray,
    right: np.ndarray,
    up: np.ndarray,
    half_w: float,
    half_h: float,
) -> list[tuple[float, float]]:
    if shape == "triangle":
        local = [(0.0, 0.58), (-0.5, -0.29), (0.5, -0.29)]
    elif shape == "ellipse":
        local = [
            (0.5 * np.cos(2.0 * np.pi * i / 32.0), 0.5 * np.sin(2.0 * np.pi * i / 32.0))
            for i in range(32)
        ]
    elif shape == "hexagon":
        local = [
            (0.5 * np.cos(2.0 * np.pi * i / 6.0), 0.5 * np.sin(2.0 * np.pi * i / 6.0))
            for i in range(6)
        ]
    else:
        local = [(-0.5, -0.5), (0.5, -0.5), (0.5, 0.5), (-0.5, 0.5)]
    points = [
        center + right * (x * half_w * 2.0) + up * (y * half_h * 2.0)
        for x, y in local
    ]
    return [(float(x), float(y)) for x, y in points]


def _foreground_mask_for_view(view_config: dict[str, Any], img_size: int) -> Image.Image:
    offset_x, offset_y = [float(v) for v in view_config.get("offset_xy", [0.0, 0.0])]
    size_x, size_y = [float(v) for v in view_config.get("size_xy", [0.28, 0.28])]
    angle = np.deg2rad(float(view_config.get("angle_degrees", 0.0)))
    shape = str(view_config.get("shape", "rectangle"))

    center = np.asarray(
        [
            (0.5 + offset_x) * img_size,
            (0.5 - offset_y) * img_size,
        ],
        dtype=np.float64,
    )
    half_w = size_x * img_size * 0.5
    half_h = size_y * img_size * 0.5
    right = np.asarray([np.cos(angle), -np.sin(angle)], dtype=np.float64)
    up = np.asarray([np.sin(angle), np.cos(angle)], dtype=np.float64)
    points = _foreground_shape_points(shape, center, right, up, half_w, half_h)
    mask = Image.new("L", (img_size, img_size), 0)
    draw = ImageDraw.Draw(mask)
    draw.polygon(points, fill=255)
    return mask


def _make_model_anchored_foreground_occluder_config(
    mesh_centered: trimesh.Trimesh,
    fronts: Sequence[Sequence[float]],
    img_size: int,
    seed: int,
    color: Sequence[int | float],
    size_min: float,
    size_max: float,
    depth: float,
) -> dict[str, Any]:
    rng = np.random.default_rng(seed)
    shapes = ("rectangle", "ellipse", "triangle", "hexagon")
    model_vertices = np.asarray(mesh_centered.vertices, dtype=np.float64) + 0.5
    anchors = np.asarray(mesh_centered.triangles_center, dtype=np.float64) + 0.5
    if len(anchors) == 0:
        anchors = model_vertices

    views: list[dict[str, Any]] = []
    for front in fronts:
        width = float(rng.uniform(size_min, size_max))
        height = float(rng.uniform(size_min, size_max))
        shape = str(rng.choice(shapes))
        projected = _project_unit_points(anchors, model_vertices, front, img_size=img_size)
        x_norm = projected[:, 0] / float(img_size)
        y_norm = projected[:, 1] / float(img_size)
        margin_x = width * 0.5
        margin_y = height * 0.5
        valid = (
            (x_norm >= margin_x)
            & (x_norm <= 1.0 - margin_x)
            & (y_norm >= margin_y)
            & (y_norm <= 1.0 - margin_y)
        )
        candidates = projected[valid] if valid.any() else projected
        anchor = candidates[int(rng.integers(0, len(candidates)))]
        offset_x = float(anchor[0] / float(img_size) - 0.5)
        offset_y = float(0.5 - anchor[1] / float(img_size))
        jitter_x = float(rng.uniform(-0.12, 0.12) * width)
        jitter_y = float(rng.uniform(-0.12, 0.12) * height)
        max_x = max(0.0, 0.5 - width * 0.5)
        max_y = max(0.0, 0.5 - height * 0.5)
        offset_x = float(np.clip(offset_x + jitter_x, -max_x, max_x))
        offset_y = float(np.clip(offset_y + jitter_y, -max_y, max_y))
        views.append(
            {
                "offset_xy": [offset_x, offset_y],
                "size_xy": [width, height],
                "angle_degrees": float(rng.uniform(-22.0, 22.0)),
                "shape": shape,
                "depth": float(depth),
            }
        )
    return {
        "color": [float(v) / 255.0 if float(v) > 1.0 else float(v) for v in (*color, 255)[:4]],
        "depth": float(depth),
        "views": views,
        "placement": "model_projected_anchor",
    }


def _apply_mask_visualization(
    image_path: Path,
    mask: Image.Image,
